/*
 * ============================================================================
 *  Name     : TAudioShared.h
 *  Part of  : SoundMixer
 *  Created  : 03/30/2006 by Forum Nokia
 *  Description:
 *     This is the project specification file for SoundMixer.
 *     Initial content was generated by Series 60 AppWizard.
 *
 *  Version  : 2.0.0
 *  Copyright: Forum Nokia
 * ============================================================================
 */

#ifndef __TAUDIOSHARED_H__
#define __TAUDIOSHARED_H__

#include "czPrivateDefs.h"


// forward declarations
namespace cz
{
	namespace audio
	{
		class SymbianOutput;		
	}
}


namespace cz
{
namespace audio
{

struct TSharedData
{
public:
	
    struct
    {
    	/*
        u32 m_samples;
        TInt m_samplerate, m_monostereo;
        */
    	TMdaAudioDataSettings::TAudioCaps numChannels;
    	TMdaAudioDataSettings::TAudioCaps sampleRate;
    	int bufSizeFrames;
		int bufSizeMicroseconds;
    } settings;

    RMutex			iMutex;
	SymbianOutput *iDriver;
    TRequestStatus*	iStatusPtr;
	RSemaphore		iAliveMutex;
	
    volatile bool m_threadStarted;
    volatile bool m_threadRunning;
    volatile bool m_playSound;
    volatile bool m_working;
	volatile bool m_fillWithSilence;
	
};

} // namespace audio
} // namespace cz
#endif
