// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---- //
// mclk //
// ---- //

#define mclk_wrap_target 0
#define mclk_wrap 1

static const uint16_t mclk_program_instructions[] = {
            //     .wrap_target
    0xe001, //  0: set    pins, 1                    
    0xe000, //  1: set    pins, 0                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program mclk_program = {
    .instructions = mclk_program_instructions,
    .length = 2,
    .origin = -1,
};

static inline pio_sm_config mclk_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + mclk_wrap_target, offset + mclk_wrap);
    return c;
}

// Helper function (for use in C program) to initialize this PIO program
void mclk_program_init(PIO pio, uint sm, uint offset, uint pin) {
    // Sets up state machine and wrap target. This function is automatically
    // generated in mclk.pio.h.
    pio_sm_config c = mclk_program_get_default_config(offset);
    // Allow PIO to control GPIO pin (as output)
    pio_gpio_init(pio, pin);
    // Connect pin to SET pin (control with 'set' instruction)
    sm_config_set_set_pins(&c, pin, 1);
    // Set the pin direction to output (in PIO)
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    // Load configuration and jump to start of the program
    pio_sm_init(pio, sm, offset, &c);
}

#endif
